---
name: ngrok Client
version: dev
slug: ngrok
description: A ngrok client for Hass.io
url: https://github.com/arimakai/hassio-addons
codenotary: codenotary@frenck.dev
startup: services
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
ingress: true
ingress_stream: true
ports:
  80/tcp: null
  4040/tcp: 4040
ports_description:
  4040/tcp: Web UI (Not required for Ingress)
options:
  log_level: info
  auth_token: ""
  region": us
  tunnels: 
    - name: hass
    proto: http
    addr: 8123
    inspect: "false"
    auth": ""
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  auth_token: str?
  region: list(us|eu|ap|au|sa|jp|in)?
  tunnels:
    - name: str
    proto: list(http|tls|tcp)
    addr: match(^((([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5]):([1-9]|[1-5]?[0-9]{2,4}|6[1-4][0-9]{3}|65[1-4][0-9]{2}|655[1-2][0-9]|6553[1-5]))|([1-9]|[1-5]?[0-9]{2,4}|6[1-4][0-9]{3}|65[1-4][0-9]{2}|655[1-2][0-9]|6553[1-5])$)
    inspect: bool?
    auth: password
    host_header: str?
    bind_tls: bool?
    subdomain: str?
    hostname: str?
    crt: str?
    key: str?
    client_cas: str?
    remote_addr: match(^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5]):([1-9]|[1-5]?[0-9]{2,4}|6[1-4][0-9]{3}|65[1-4][0-9]{2}|655[1-2][0-9]|6553[1-5])$)?
    metadata: str?
